### ISSUE TITLE
Decrease Time Complexity

### ISSUE THREAD

**Issue by Devolopia** [Devolopia/Bits#3]
I think we need to decrease the time complexity of Number of Set Bits

**Comment by Devolena** [comment]
If we use (n & n-1) then time complexity decreases to number of set bits because in every iteration we remove one set bits till we reach to zero.

**Comment by Devolopia** [comment]
> If we use (n & n-1) then time complexity decreases to number of set bits because in every iteration we remove one set bits till we reach to zero.

Yes may be its is efficient approach!
